### PR TITLE
add flag for allow comment both at and is

### PR DESCRIPTION
**Pull request by Sivanwol**
HI i added new flag that i saw that missing that called 
comment
i got a project that need allow comments in a model 
so this good place put this please note will add more as i see hehe 
also will mark if the test not pass

### CODE REVIEW

**Comment by antonkomarev** [comment]
What does this flag means?

**Comment by antonkomarev** [comment]
Name is not obvious. At least it should be named `is_commentable`, but I'm not sure it's a good place to do the thing. I'd prefer to create separate model which will handle comments of the model, if this model exists - you can add comments to it, otherwise not.

**Comment by Sivanwol** [comment]
ok about the name done i change at you right it has no sense or more current i got no name sense hehe
but the split of modle done sure what u mean

**Comment by antonkomarev** [comment]
@Sivanwol thank you for the PR, but I'm not ready to add it to this package. As for me it seems wrong way. You could add it in your project.

**Pull request closed without merging**
