### PR TITLE
Fire events

### PR DESCRIPTION
**Pull request by jonagoldman**
Fire events on actions. Related to https://github.com/cybercog/laravel-eloquent-flag/issues/4 and https://github.com/cybercog/laravel-eloquent-flag/issues/33.
No tests added.

### CODE REVIEW

**Comment by a-komarev** [comment]
Thank you for the PR, Jona! It would be great to have a tests for this events too.

**Comment by jonagoldman** [comment]
The 2nd argument is used to allow/disallow the event listener to stop the propagation.
This will be used in events that are fired before the method execution.
For example, if we had an `accepting` event, it will like like this:

```php
/**
 * Mark entity as accepted.
 *
 * @return void
 */
public function accept()
{
    $this->fireModelEvent('accepting'); // $halt defaults to true
    $this->setAcceptedFlag()->save();
    $this->fireModelEvent('accepted', false);
}
```

In this case, the listener to the `accepting` event can `return false` and `$this->setAcceptedFlag()->save();` will not be triggered. I don't think we need this functionality right now.

Regarding tests... I must confess I have not a done much testing in my projects so I think you will need to help me on this one.

**Comment by a-komarev** [comment]
Okay, I'll merge this changes, and we will return to tests a bit later this week.

**Comment by a-komarev** [comment]
@jonagoldman thank you for researching topics about this feature compiling all this stuff down!

**Pull request merged**
